### ISSUE TITLE
일반로그인 & SSO로그인 관련

### ISSUE THREAD

**Issue by seminlee0** [rchemist/demo-micro-front-mono#1]
**### 일반로그인**
1. 회원가입 호출 이후에 그 데이터로 로그인 진행
2. '캐시에 없음' 메세지 출력 후 throw new InternalAuthenticationServiceException("UserDetailsService returned null."); 익셉션 발생
```
Response Body Data
{
    "data": null,
    "error": {
        "error": true,
        "status": 500,
        "errorType": null,
        "message": "UserDetailsService returned null.",
        "fieldError": {}
    }
}
```

**### 여기서, 궁금한 점**
1. globalauthenticationprovider: ResponseData<AuthenticationResponse> data = (ResponseData)resultHolder.getResult();
data 값이 null이 아니게 되려면 어떻게 해야 하는지 확인 부탁드립니다.

2. 로그인이 완료되었다면, 모듈에 있는 클래스에서 유저정보를 시큐리티에 담아두게 되는 것이 아닐까요? 
시큐리티 관련 커스터마이징을 하게 된다면 어떠한 것들을 추가적으로 진행해야 하는지 가이드 부탁드립니다. (예시 필요)

3. SSO로그인을 하게 될 경우의 설명이 메일로는 정확하게 이해가 되질 않습니다. 일반 로그인이 된 사용자 또는 자동 로그인 설정이 되어 있다면 CustomerAuthenticationServiceImpl.requestSignin 메소드를 호출하면 되는 걸까요? 이때, 토큰 사용절차에 대해 다시 한번만 설명해주시면 감사하겠습니다.
  **** 여기서 platform.config.customer.simple-authentication: true가 설정이 되었다는 가정**

**Comment by kunner** [comment]
안녕하세요. 

각 항목에 답변 드리기 앞서 현재 구현 중인 코드를 좀 보고 싶습니다. SpringSecurity 설정 내역을 확인하면 좋겠어서요. 리파지토리를 공유해 주시면 답변 드리거나 문제 해결이 쉬워 질 듯 합니다.

**Comment by seminlee0** [comment]
안녕하세요.

현재는 기능이 정상적이지 않아서 익셉션이 발생하실 겁니다. 양해 부탁드리겠습니다.
레포지토리는 아래와 같으며 계정은 문홍인 이사님 계정으로 깃랩 권한 넣어두었습니다.

https://gitlab.reflexion.co.kr:9000/ceragem/ceratalktalk-front/-/tree/dev
Email: hongin@rchemist.io (문홍인 이사님 계정)

**Comment by kunner** [comment]
https://github.com/rchemist/demo-micro-front-mono/commit/e6e819510dd53df7c055f85ddce36b469d095216 를 확인해 주세요.

샘플 SpringSecurity 설정과 @Secured 설정 처리가 되어 있으며,
로그인/로그아웃, 현재 세션 정보 확인 등을 어떻게 처리하면 되는지 샘플 코드가 작성되었습니다.

마찬가지로 로그인할 때 비밀번호 체크를 하지 않으려면 platform.config.customer.simple-authentication=true 로 설정해야 합니다.
(세라톡톡의 경우는 true, 커뮤니티의 경우는 false 가 맞습니다)

그 외 application.properties 는 그대로 유지합니다.

**Comment by rchemist** [comment]
각 질문에 추가로 답변 드리면,

1. 샘플 코드를 사용하면 globalAuthenticationProvider 가 null 이 되지 않습니다. 그냥 사용하시면 됩니다.

2.로그인이 완료되면 SprintSecurityContext 에 저장되며, 관련한 사용법은 샘플코드를 참고 하시기 바랍니다. (SimpleAuthentication 을 사용하면 플랫폼 코드 실행에 필요한 다양한 정보가 함께 제공됩니다)

3. SSO 로그인은 다음 두 가지 방법으로 구현할 수 있습니다.
   1) OAuth2 기반 로그인을 구현해 SSO 로그인을 처리하는 방법: 이 방법이 정석이며, 이 경우 구현해야 할 코드가 다소 많아집니다. SpringSocial 을 참고하면 됩니다.
   2) OAuth2 기반 로그인을 구현하지 않고 단순 로그인 처리 하는 방법
       세라톡톡의 경우 별도의 회원가입 없이 무조건 회원동기화가 되는 방식이므로, 굳이 많은 코드를 개발할 필요가 없습니다. 
       Naver 측 로그인 결과에 따라 로그인이 성공하면 해당 정보를 가지고 gatewayTokenAuthenticationService.createAccessToken(tokenRequest) 를 호출하면 됩니다. (SecurityTestController#loginTest() 참고)

그럼, 추가로 설명이 필요한 부분이 있다면 말씀 주시기 바랍니다.

**Comment by seminlee0** [comment]
답변 감사합니다. 해당 내용을 토대로 진행해보도록 하겠습니다.

추가 문의사항 요청드립니다. 이 부분은 제가 잘못 호출을 하고 있는건지 확인 부탁드립니다.

### Customer 회원가입: /customer/authentication/register
> 3월24일 호출할 때는 test16 계정명으로 생성됐지만, 3월29일 호출 시 아래와 같이 예외처리 되어 가입처리 진행 안되고 있습니다.
**Request**
```
{
    "username": "refltest1",
    "name": {
        "firstName": "철수",
        "lastName": "홍"
    },
    "emailAddress": "refltest1@gmail.com",
    "password": "asdasd1!",
    "countryCode": "82",
    "phoneNumber": "01087654321",
    "siteAlias": "defaultsite",
    "siteType": "FRONT",
    "tenantAlias": "defaultTenant",
    "address": {
        "country": "Korea",
        "state": "Seoul",
        "city": "Seoul",
        "address1": "영등포구 여의대방로 43라길 8",
        "address2": "111동 1303호",
        "addressDetail": "추가 주소 입력 필드",
        "postalCode": "07351"
    }
}
```

**Response**
```
{
    "data": null,
    "error": {
        "error": true,
        "status": 404,
        "errorType": "SITE_NOT_FOUND",
        "message": "Site 정보를 찾을 수 없습니다.",
        "fieldError": {}
    }
}
```


### Customer 로그인
/security-test/login-test?userId=test16&password=a00000000!
또는 /security-test/login-test?userId=test16@gmail.com&password=a00000000!
> "자격 증명에 실패하였습니다." 메세지 출력
> 파라미터 인자가 틀린 것인지 확인 요청 드립니다. 새로운 회원가입을 통해 재확인을 해보려했지만, 회원가입이 진행되지 않습니다.


바쁘신 와중에 대응해주셔서 감사합니다.

**Comment by kunner** [comment]
사이트 alias 제약 부분의 코드가 약간 변경 됐습니다. site alias 를 defaultSite 로 해 보세요.

**Comment by seminlee0** [comment]
위에 문의드린 내용에서도 defaultsite로 테스트를 진행했습니다.
알케미스트 개발서버에서 회원가입을 진행 시 정상적으로 가입이 되지만, local에서 테스트를 진행하면 아래와 같이 응답이 됩니다. local에서 요청할 때 선행조건이 있어야 하는 것이 있을까요? 물론, local에서는 회원가입이 없기 때문에 해당 질문이 무의미 하긴 합니다만, 요청이 정상적이지 않아서 확인이 필요했습니다. 
회원가입은 확인만 부탁드리며, **로그인 기능에 대한 답변 및 가이드 부탁드립니다.**
```
{
    "data": null,
    "error": {
        "error": true,
        "status": 404,
        "errorType": "SITE_NOT_FOUND",
        "message": "Site 정보를 찾을 수 없습니다.",
        "fieldError": {}
    }
}
```


로그인 관련하여 전달주신 **/security-test/login-test** 시큐리티 테스트로 로그인 진행 시 정상적으로 되시는지 확인해주시면 감사하겠습니다.

**Comment by hongin81** [comment]
일단 로컬에서 요청할 때 라는 것이 데이터베이스를 로컬에 설치하고 신규로 개발 환경을 구축한 것을 말씀하신건가요? 

만약 로컬에 구성을 하게 되면
 1. 기본 테넌트 자동 생성 (defaultTenant)
 2. 기본 권한 생성 (ROLE_USER, ROLE_ADMIN)
 3. 기본 관리자 자동 생성
    - id : admin
    - pw : 랜덤 생성 (최초 실행시 로그에 비밀번호가 출력됩니다.)

관리자 도구에 생성된 관리자로 로그인하여 프론트 사이트 생성 한 후에 회원 가입 API 를 호출하셔야 합니다. 
사이트 생성시 입력한 siteAlias 를 API 호출시 이용하셔야 합니다.
