### ISSUE TITLE
내가쓴글 리스트 출력 관련

### ISSUE THREAD

**Issue by seminlee0** [rchemist/demo-micro-front-mono#11]
안녕하세요.

**"내가쓴글"** 리스트만 출력하기 위해 PostSearchForm.profileId에 데이터를 담아서 boardManageService.searchPosts(searchForm); 으로 데이터 요청하려고 합니다.

이때, profileId를 사용하기 위해 세션에 있는 customerId를 이용하여 profileId를 꺼내려고 하는데
현재 boardManageService.searchProfiles(searchForm); 으로 데이터 요청할 때 ProfileSearchForm 안에 name으로만 검색이 가능할까요?
customerId로 검색은 불가능한걸까요?

아니면, 다른 방법으로 profileId를 추출해야한다면 가이드 부탁드리겠습니다.

감사합니다.

**Comment by hongin81** [comment]
PostSearchForm 에 "createdBy" 에 customerId 를 넣어서 검색하면 됩니다.
예) { "createdBy": "99cb5232-0736-42fe-a424-b6b078a80461"}
