### ISSUE TITLE
아이디 정규표현식 관련

### ISSUE THREAD

**Issue by maketext** [rchemist/demo-micro-front-mono#14]
안녕하세요. 

회원의 Username 필드의 정규표현식이

기존 정책상 소문자 또는 대문자 1개 이상 숫자 포함 총 5자 이상인 것으로 확인되고 있습니다.

하지만 저희가 추가할 회원의 아이디는 숫자 only, 언더바 특수문자 포함, 3자 길이 가 포함되어 있습니다.

예를 들어

abc

01000000000

add_add

제가 어드민 사이트에서 이를 조정할 수 있다면 간단히 안내해 주시면 감사하겠습니다.

**Comment by kunner** [comment]
application properties 를 사용해 Customer(회원) 과 AdminUser(관리자) 를 생성/수정할 때 아이디와 비밀번호의 정규식 패턴을 변경할 수 있습니다.

**이 기능을 사용하려면 먼저 메이븐으로 플랫폼의 새 버전을 다운해야 합니다.**

- 아이디(USERNAME)
  - platform.config.common.validate.regex.username
  - 설정된 값이 없으면 io.rchemist.common.util.type.RegexType.Regex.USERNAME 사용

- 비밀번호
  - platform.config.common.validate.regex.password
  - 설정된 값이 없으면 io.rchemist.common.util.type.RegexType.Regex.PASSWORD 사용
