### ISSUE TITLE
article DeleteAsset 기능 관련 문의

### ISSUE THREAD

**Issue by cijReflexion** [rchemist/demo-micro-front-mono#17]
게시판에서 게시글 내용을 수정할 때,
이미 업로드된 게시물 중 일부를 삭제하는 기능을 구현하려 하고 있습니다.

현재 ArticleUpdateRequest에 DeleteAssets에 List를 변수로 받아 asset을 삭제하는 구조로 보이는데,
삭제할 asset의 AssetKey값을 List로 담아 삭제를 진행해 봤으나 어떤 반응을 보이고 있진 않습니다.
수정 페이지 특성상 asset 삭제와 추가 업로드가 동시에 일어날 수 있는데, 추가 업로드는 잘 진행되고 있습니다.

혹시 방법이 잘못됐는지 문의 드립니다.

**Comment by hongin81** [comment]
DeleteAsset 에 List 로 담는 String 값은 Key AssetKey 값이 아닙니다.
asset 의 도메인 정보가 빠진 Url 정보입니다.

Url 정보를 보내실 때에 다음과 같은 형식으로 보내야합니다. fileSize 는 필수값은 아닙니다.
 - {assetUrl}?assetKey={assetKey}&fileSize={fileSize}

예) 
호출 URL : http://localhost:8110/cms/board/board_notice/article/Oyky4204b-cbfa
호출 DATA
{
    "boardAlias": "board_notice",
    "deleteAssets": [ "/static-resource/다운로드.png?assetKey=yMMQ834b1b1e35" ]
}

**Comment by cijReflexion** [comment]
네 해결됐습니다 감사합니다
