### ISSUE TITLE
게시글 목록 검색 조건으로 NoticeType을 추가해주셨으면 합니다.

### ISSUE THREAD

**Issue by cijReflexion** [rchemist/demo-micro-front-mono#18]
현재 게시글 목록을 조회할때 공지사항을 우선 조회 한 다음, 
일반 게시물을 조회하는 순서로 목록을 호출하려 합니다.

이 두개의 게시물을 구분하기 위해 NoticeType을 이용하려 하는데, 
현재 ArticleSearchForm에는 NoticeType을 받을 수 없어 보입니다.

현재로썬 공지글과 일반글을 구분하는 방법으로 NoticeType이 가장 확실해 보여 이걸 목록조회 조건으로 추가하고 싶은데,
검색 조건으로 사용할 수 있게 추가해 주실 수 있는지 문의 드립니다.

**Comment by hongin81** [comment]
ArticleSearchForm 에서 boardAlias 를 넣어서 조회하시면 됩니다.
boardAlias 는 게시판 생성시 이미 알고 있는 키이고 중복될 수 없는 값 입니다.
noticeType 은 공지글 여부를 나타내는 것입니다. 추후 커뮤니티에서 게시판 공지, 전체 공지 등 구분값을 주려고 만들어놓은 필드입니다.

**Comment by cijReflexion** [comment]
네 제가 하려는 의도가 말씀하신 게시판 공지 기능과 같습니다
같은 boardAlias 값을 가지고 있는 같은 게시판의 게시물 사이에
관리자만 올릴 수 있는 게시판 공지 글이 있고, 이 게시판 공지 글을 고정으로 최상단에 띄우게 하려는 의도 입니다

현재 전체 공지에 해당하는 글은 별도의 boardAlias를 가지고 있는 것 역시 이미 구현해 놓은 상태 입니다

현재 noticeType을 사용할 수 없는 상태라면 topic으로 공지를 등록해서 구분 사용해야 할 것 같은데
topic 역시 공지가 아닌 글을 구분하여 검색하기 위해선 특정 topic이 아닌 글에 대해 not 연산이 필요 할 것 같습니다.

**Comment by hongin81** [comment]
ArticleSearchForm.withSort(ArrayUtil.make("noticeType asc", "created.createdAt desc") 
로 검색하시면 noticeType 이 Board 인게 최상위로 올라오게 됩니다.
이렇게 검색하시면 됩니다.

**Comment by cijReflexion** [comment]
noticeType이 공지글이 아닌 게시글만 검색할순 없을까요?
지금 구현하려는게 처음에 공지글을 불러 온 다음 
공지글이 아닌 글을 20개씩 페이징 처리 하려고 합니다

**Comment by hongin81** [comment]
noticeType 추가했으며, 배포후에 말씀 드리도록 하겠습니다.

**Comment by hongin81** [comment]
배포하였으니 확인 해보세요

**Comment by cijReflexion** [comment]
확인하였습니다 감사합니다
