### ISSUE TITLE
운영서버 DB설정 관련

### ISSUE THREAD

**Issue by seminlee0** [rchemist/demo-micro-front-mono#19]
안녕하세요.

현재 운영서버에서 알케미스트 측 DB를 바라보고 있습니다.
설정을 변경하려고 하는데, resources/service-propertis 부분의 *-production.yml 파일들의 변경이 필요할까요?

확인해주시면 감사하겠습니다.

**Comment by hongin81** [comment]
최종적으로 해당 프로젝트 맨 바깥쪽 application-production.yml 을 바라봅니다.
어떤 데이터가 알케미스트 데이터 베이스를 바라본다는 건가요?

**Comment by seminlee0** [comment]
현재 게시판의 게시글들의 내용은 알케미스트 DB를 바라보고 있습니다.
해당 데이터들은 운영DB에서는 존재하지 않아서 위와 같이 요청드렸습니다.
