### ISSUE TITLE
CustomerDTO lastLoggedIn 컬럼 null

### ISSUE THREAD

**Issue by seminlee0** [rchemist/demo-micro-front-mono#24]
안녕하세요.

lastLoggedIn의 값이 null로 담겨 있습니다.

이 데이터는 어떤 업데이트를 쳐야 하는지 가이드 부탁드립니다.

**Comment by kunner** [comment]
프론트에서 로그인하면 자동으로 채워지는 정보 입니다.

따로 업데이트를 할 필요는 없으며, 현재 오동작 하고 있는 것 같아 확인 후 조치 하겠습니다.

**Comment by kunner** [comment]
로그인 기록 저장 기능 수정해 배포 했습니다.

- 로그인 성공 시
  실패 카운트 초기화, 마지막 로그인 시점으로 인식

- 로그인 실패 시 
  실패 카운트 증가(없으면 1), 마지막 로그인 시점과 관계 없음
