### ISSUE TITLE
조회수 카운팅 관련

### ISSUE THREAD

**Issue by seminlee0** [rchemist/demo-micro-front-mono#25]
안녕하세요.

게시판 조회수 관련해서 카운팅의 대한 기능이 정상동작하지 않는 것인지, 기능이 없는 것인지 파악은 안됐습니다만, 전달 받기로는 현재 정상적이지는 않은 것 같습니다.

이 부분 확인 부탁드리겠습니다.
부가적인 내용이 추가적으로 필요하시다면, 전달 받아서 말씀드리겠습니다.

**Comment by hongin81** [comment]
ArticleDTO 의 viewCount 필드에서 조회수를 확인하실 수 있으며,
viewCount 를 올리시기 위해서는 BoardManageServiceImpl 의 increaseArticleViewCount(ArticleViewCountRequest request) 를 호출하시면 됩니다. 

그리고 ArticleCreateRequest 를 이용하여 Article 생성하실 때, 세라톡톡은 반드시 boardType = BOARD 로 넘겨주시기 바랍니다.

**Comment by cijReflexion** [comment]
객체 ArticleCreateRequest 에 게시물 ID, boardAlias, 사용자 ID를 담아
increaseArticleViewCount 메소드에 조회수 증가 요청을 하고 있습니다.
조회수가 0에서 1로 증가가 되는데, 1 이상으론 아무리 반복 요청을 하고 다른 계정으로 들어와서 조회를 해도 오르지 않습니다.

현재 조회수 증가 로직 -> 게시물 조회 로직 순으로 진행되고 있습니다.
오류가 있는건지, 요청중에 누락된게 있는지 문의 드립니다

**Comment by hongin81** [comment]
전체 조회수 가져오는 부분 수정하였습니다. 
테스트 부탁드립니다.
