### ISSUE TITLE
게시판 본문이 길면 등록이 안되는 문제

### ISSUE THREAD

**Issue by ecips740** [rchemist/demo-micro-front-mono#26]
이 정도 올리면 등록이 안됩니다.
![image](https://user-images.githubusercontent.com/24597803/162575133-ea286f9c-5946-4d67-a03d-334f9b717b9f.png)

이 정도 올리면 등록이 됩니다.
![image](https://user-images.githubusercontent.com/24597803/162575153-237bcb07-d953-4e30-8d88-710ae1fa810e.png)

**Comment by rchemist** [comment]
DB 컬럼이 잘못 만들어져 있었습니다.

지금 다시 해 보시면 잘 될거에요.
