### ISSUE TITLE
삭제된 글이 리스트에서 삭제된 글입니다 로 계속 표기됩니다.

### ISSUE THREAD

**Issue by cijReflexion** [rchemist/demo-micro-front-mono#29]
댓글이 달린 글은 삭제를 해도
삭제 처리나 비전시 처리가 되지 않는 것 같습니다.
기존의 active나 achived값의 변동으로 인한 soft delete처리가 아닌 TEMPORARY_DELETE 값에만 변동이 있는 것 같은데
searchform에서도 이 값을 통해 검색해서 삭제 처리된 글을 거를 수 있어야 할 것 같습니다

**Comment by hongin81** [comment]
검색 정보에 해당 필드 넣도록 하겠습니다.
또한, 게시판 생성시 댓글이 달려있어도 즉시 삭제 할 수 있는 설정값도 함께 넣어두도록 하겠습니다. 

6시 배포 후에 확인 부탁드립니다.

**Comment by hongin81** [comment]
관리자도구 > 게시판 > 상세에 들어가보면 '게시물 임시 삭제 사용 여부' 를 선택하게 만들었습니다.
게시물 하위에 댓글이 있을 경우, 즉시 삭제하는 대신 삭제된 게시글입니다 라고 표현되는 것을 원하시면 사용 여부를 '예'로 해주시면 됩니다.

세라톡톡은 즉시 삭제하는 것을 요청했기 때문에 모든 게시판에 해당 값을 '아니오'로 세팅해두었습니다.


<img width="1516" alt="스크린샷 2022-04-14 오후 10 11 06" src="https://user-images.githubusercontent.com/13640100/163398618-9d35f2e1-2255-4ba9-9444-d54fecc42b72.png">
