### ISSUE TITLE
게시글 검색 메소드 (boardManageService.searchPosts)  사용법 문의합니다

### ISSUE THREAD

**Issue by cijReflexion** [rchemist/demo-micro-front-mono#3]
현재 boardManageService.searchPosts 메소드를 통해 게시물 목록을 조회하고 있습니다.
setPage와 pageSize, active 등을 통한 페이징은 잘 적용되고 있어 목록을 불러 오는데 문제가 없지만,

setTitle과 setContent에 내용을 담아 검색을 하려하니 해당 검색 내용이 반영되지 않고 전체 목록을 조회하고 있습니다.
혹시 방법이 잘못 된 건지 문의 드립니다

현재 관련 라이브러리는 29일 버전을 사용하고 있습니다 (micro-cms-0.0.1-20220329.125108-19.jar)

추가로 제목+내용 검색 기능도 필요 한데 이 부분 OR 조건 검색이 가능 한지도 여쭤봅니다

**Comment by hongin81** [comment]
사용법은 맞습니다. 검색 대상 필드에 추가가 안되어 있어 추가하고 제목과 타이틀이 같이 들어왔을때 OR 검색할 수 있도록 추가하도록 하겠습니다. 수정 및 테스트 후 배포하고 커멘트 남겨놓도록 하겠습니다

**Comment by cijReflexion** [comment]
네 감사합니다

**Comment by cijReflexion** [comment]
혹시 or 검색 기능에 대해 추가된 사항이 있을까요?

**Comment by hongin81** [comment]
ArticleSearchForm 이용하셔서
operator 에 OR 로 하시고 title 과 content 입력해주시면 됩니다.

배포 되었습니다.

**Comment by cijReflexion** [comment]
ArticleSearchForm articleSearchForm = ArticleSearchForm.builder()
                .boardAlias(BOARD_ALIAS)
                .build();
articleSearchForm.setActive(true);
articleSearchForm.setNoticeType("NONE");
articleSearchForm.setTitle(search.getValue());
articleSearchForm.setContent(search.getValue());
articleSearchForm.setOperator(ConditionOperatorType.OR);

검색 로직상에 이렇게 처리를 했고
결과로 나간 쿼리를 봤을 때 (콘솔 로그)

where
	( (article0_.IS_ARCHIVED is null
		or article0_.IS_ARCHIVED = 0))
	and **_(lower(article0_.BOARD_ALIAS) like ?
		or lower(article0_.TITLE) like ?
			or lower(article0_.CONTENT) like ?
				or article0_.NOTICE_TYPE =?
				or article0_.IS_ACTIVE =?)_**

다음과 같이 searchForm에 넘겨준 모든 값이 or문으로 연결되었습니다.
그러다 보니 검색 파라미터와 상관 없이 모든 게시물이 결과로 나오고 있습니다.

다른 조건들은 and 이지만 title과 content에 대해서만 선택적으로 or 검색 하는 방법이 필요합니다.

**Comment by hongin81** [comment]
ArticleSearchForm 에 operator 는 and 로 변경하시고,
title + content 로 검색 할 경우 searchTerm 에 해당 값을 넣어서 검색해주세요.

이 부분 수정 부탁드립니다.
