### ISSUE TITLE
댓글 태그 삽입되어서 내려오는 이슈

### ISSUE THREAD

**Issue by seminlee0** [rchemist/demo-micro-front-mono#31]
안녕하세요.

현재 프론트에서 댓글의 데이터가 태그가 달린 형태로 내려오고 있어서 관리자에서 확인해보니 프론트에서 사용하지 않는 기능들(에디터, 파일 업로드 등)이 존재하는 것으로 파악됩니다.

만약, 에디터가 그대로 사용이 되어야 한다면, XSS에 대하여 검증 후에 데이터를 내려보내 주시는 걸까요?

그렇다면, 타임맆을 이용하여 태그 형태의 값을 그대로 적용해서 사용하려고 합니다.

**Comment by kunner** [comment]
관리자에서 입력하는 정보에 한해 XSS 처리 됩니다.

Front 에서는 XSS 처리를 직접 하거나, 내장된 XssFilter 를 Security 설정에 추가해야 합니다.

내장된 XssFilter 는 다음과 같습니다.
io.rchemist.common.security.filter.XssFilter

**Comment by kunner** [comment]
이 이슈는 해결된 것으로 알고 있습니다. 이슈를 닫겠습니다.
혹시 문제가 지속되면 이슈를 다시 열어 주시기 바랍니다.
