### ISSUE TITLE
[버그]로그인 실패 성공에 대한 count

### ISSUE THREAD

**Issue by jonghankim** [rchemist/demo-micro-front-mono#32]
![image](https://user-images.githubusercontent.com/13681434/163660428-ba3ec4dc-8ef4-46e0-8cf1-794fd57fd05b.png)

[테스트 내용]
1. 로그인 실패 --> 실패:1
2. 로그인 실패 --> 실패:2
3. 로그인 성공 --> 실패:0
4. 로그인 실패 --> 실패:3

4번에서 실패 건수가 1로 세팅 되어야 하지 않을까요?

**Comment by rchemist** [comment]
네, 버그가 맞네요. 

CustomerJpaExtensionHandler#loginTrace() 에서 최근 로그인 정보를 가져와야 하는데 성공한 정보만 가져 오고 있었고,
```java
CustomerLoginTrace lastTrace = getLastCustomerLoginTrace(customerId, true);
```

CustomerJpaExtensionHandler#getLatestFailedCount() 에서도 역시 최근 로그인 정보를 가져와야 하는데 실패한 정보만 가져오고 있었습니다.
```java
CustomerLoginTrace trace = getLastCustomerLoginTrace(customerId, false);
```

각각 뒤의 success 변수가 null 로 셋팅되어야 맞습니다.

AdminUser 쪽에도 동일한 이슈가 있어 함께 변경했습니다.

해당 내용 변경해 바로 배포해 놓겠습니다.

감사합니다.

**Comment by rchemist** [comment]
배포 했습니다, 확인해 보시고 문제 없으면 이슈 클로즈 부탁 드립니다~

**Comment by jonghankim** [comment]
정상 확인 했습니다.
감사합니다.
