### ISSUE TITLE
프론트서버 에러로그 관련

### ISSUE THREAD

**Issue by seminlee0** [rchemist/demo-micro-front-mono#33]
안녕하세요.

프론트 운영서버에서 현재 아래와 같은 에러가 나타나고 있습니다.
`Method getTopics is not found at io.rchemist.cms.board.data.ArticleSearchForm`

현재 getTopic만 사용하고 있지만, 위와 같이 로그가 지속적으로 올라오고 있습니다.
혹시 라이브러리에서 호출되는 에러가 아닐지 확인 요청드립니다.

감사합니다.

**Comment by kunner** [comment]
이 로그는 디버그로 변경될 예정입니다. 어플리케이션 동작과는 별 관계가 없으므로 close 하겠습니다.
