### ISSUE TITLE
article의 커버 이미지 관리 방법

### ISSUE THREAD

**Issue by jonghankim** [rchemist/demo-micro-front-mono#34]
article에 커버 이미지 저장 공간이 없습니다.

aticle에 List<AttachAsset> articleAssets = new ArrayList(); 
첨부 파일만 존재함.

**Comment by hongin81** [comment]
어제 말씀드린것과 같이 Asset 등록시 tag 등록 가능하게 수정 예정입니다. 
해당 부분 수정하게 되면, 이미지 tag 를 이용해서 커버이미지 구분지어 사용하시면 됩니다.
