### ISSUE TITLE
article에서 다음글, 이전글 처리 방법

### ISSUE THREAD

**Issue by jonghankim** [rchemist/demo-micro-front-mono#35]
프론트에서 공지사항, FAQ에 상세조회 화면에 이전글, 다음글 이 존재 합니다.

이부분을 어떻게 처리 하는 것이 좋을지 의견 부탁 드립니다.

**Comment by kunner** [comment]
이전글, 다음글 찾는 API 를 만들어 제공해 드리겠습니다.

작업이 완료되면 이 이슈에 다시 코멘트 하겠습니다.

**Comment by jonghankim** [comment]
ArticleDTO
- getPreviousId : 이전글 아이디
- getNextId : 다음글 아이디
