### ISSUE TITLE
article의 첨부파일에 다운로드 기능 구현 방법

### ISSUE THREAD

**Issue by jonghankim** [rchemist/demo-micro-front-mono#36]
article의 첨부파일에 다운로드 기능 구현 방법에 대해 문의 드립니다.

**Comment by kunner** [comment]
대표님, 첨부파일을 다운로드 하는 기능을 구현한다는게 어떤 뜻인가요?

**Comment by jonghankim** [comment]
AttachAsset.assetUrl 을 이용하면 AssetViewController 에서 알아서.. 브라우저로 리소스가 내려 오네요...
이걸 이용하면 될것 같습니다.
