### ISSUE TITLE
1:1 문의 에 대한 구현 관련

### ISSUE THREAD

**Issue by jonghankim** [rchemist/demo-micro-front-mono#37]
1:1 문의를 진행하고 있습니다.

1. 답변상태를 확인 할수 있는 방법이 있나요?
- 예) feedbackSummary 존재여부, approved 등
2. 답변이 있는 경우 답변 내용은 어떻게 가져오나요?
- 예) feedbackSummary 의 내용을 이용하여 가져옴.

**Comment by hongin81** [comment]
관리자도구 > 게시판 > 게시판 관리를 통해 1:1 문의 게시판을 생성하셨다면, 아래와 같이 생성하시면 됩니다.
1. 피드백 사용 여부는 False 로 처리
2. 익명으로 글을 남길 수 있게 하려면 익명 사용 여부를 True 로 생성
3. 승인 처리는 필요 없기 때문에 False 로 생성 
4. 만약 댓글을 쓰지 못하게 하려면 "댓글 권한 없음" 으로 생성

답변상태에 대해서 Status 를 관리하고 있지 않으며, 문의글 (Article) 에 대한 답변 (Comment) 으로 답변 여부를 체크하여야 합니다.
답변은 BoardController#searchComment 를 이용하여 답변을 가져오시면 됩니다.
