### ISSUE TITLE
article 등록 시점에 첨부파일 처리 방법

### ISSUE THREAD

**Issue by jonghankim** [rchemist/demo-micro-front-mono#38]
article 등록 : ResponseData<ArticleDTO> createArticle(ArticleCreateRequest request); 을 사용하려고 합니다.

첨부파일부분 : ArticleCreateRequest.assets  ==> AttachAsset 생성 필요함.
- 파일을 업로드후 결과값 = AssetUploadResult return 받음.
- AssetUploadResult 을 이용하여 AttachAsset 를 만들어야 하는데, 

[AttachAsset]
- assetKey, fileSize, assetUrl, assetTags 중에서 어떤 값을 넣어 줘야 하나요?
==> fileSize, assetUrl, assetTags 이 3개를 넣어 줘야 하나요?

위와 같이 처리 하면 될까요?

**Comment by hongin81** [comment]
파일 업로드 후 결과값을 받고 나면 uploadFileUrl?assetKey={key}&fileSize={size} 가 리턴되며, 
AttachAsset 생성시
 위 정보를 이용하여, fileSize, assetUrl, assetKey 를 기본적으로 넣어줘야 합니다.
만약, Article 에 썸네일, 첨부파일 등 구분이 필요하시다면 assetTags 에 정보를 넣어주셔야 합니다.
