### ISSUE TITLE
고객정보 조회(customerManageService.getCustomerDTO(tenantAlias, customerId)) 문의

### ISSUE THREAD

**Issue by seminlee0** [rchemist/demo-micro-front-mono#4]
안녕하세요.

먼저, 에러로그부터 전달 드립니다.
`Could not write JSON: Infinite recursion (StackOverflowError); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: io.rchemist.common.presentation.component.field.upload.UploadFile["attachAsset"]->io.rchemist.common.jpa.domain.embedded.AttachAsset["uploadFile"]->io.rchemist.common.presentation.component.field.upload.UploadFile["attachAsset"]->io.rchemist.common.jpa.domain.embedded.AttachAsset["uploadFile"]-> (반복)`

위와 같이 순환참조가 일어나고 있습니다.
해당 부분에 대한 가이드를 보내주신 알케미스트_API 문서에서 확인해봤으나, 관련 내용은 없는 것 같아서 사용법에 대해서 가이드 주시면 감사하겠습니다.

**Comment by hongin81** [comment]
MultiFile Upload 후 조회시 발생되고 있는 문제로 현재 확인 중에 있습니다.
확인 후에 커멘트 남기도록 하겠습니다.

**Comment by hongin81** [comment]
해당 부분 수정하여서 배포하였습니다.
확인 부탁드립니다.
