### ISSUE TITLE
article 추가 필드 요청

### ISSUE THREAD

**Issue by jonghankim** [rchemist/demo-micro-front-mono#41]
스토리에 소제목이 존재 하는데.. 저장할 공간이 없습니다.

혹시 article에는 attribute등 추가 필드를 저장할 공간이 없나요?

**Comment by hongin81** [comment]
게시판 생성시에 추가 필드 그룹을 설정하실 수 있습니다.
먼저 관리자 도구 > 다이나믹 컨텐츠 > 필드 (게시판별로 필요한 필드) > 필드그룹 생성
관리자 도구 > 게시판 생성 시 또는 업데이트 > 고급 설정 탭에 보시면 필드 설정하게 되면

해당 게시판 아래 생성되는 게시물들은 설정된 필드를 사용하실 수 있습니다. 

1. 생성시
<img width="908" alt="스크린샷 2022-05-09 오후 3 04 10" src="https://user-images.githubusercontent.com/13640100/167349778-e05ff918-02ce-4d9c-bf72-93ff280a922f.png">

2. 조회시
<img width="973" alt="스크린샷 2022-05-09 오후 3 04 30" src="https://user-images.githubusercontent.com/13640100/167349827-f5739290-50b8-40ce-8e73-90f263090bd3.png">
