### ISSUE TITLE
게시물 파일 업로드시 post와 asset의 참조관계 맺는 법 문의 드립니다

### ISSUE THREAD

**Issue by cijReflexion** [rchemist/demo-micro-front-mono#6]
게시물 작성시 파일 업로드 기능을 구현하기 위해
assetManageService.uploadAssetUsingForm 메소드를 사용하여 파일 정보를 asset으로 저장한 후

boardManageService.createPost 메소드의 파라미터 객체인 PostCreateRequest 를 생성하여 
게시물 작성 내용 및 위 파일정보 객체인 asset을 AttachAsset 리스트로 만들어 setAssets 를 통해 입력 하였습니다.

이와 같이 진행 한 경우 게시물 작성은 정상적으로 이루어 지고, 파일 정보 역시 asset정보로 저장이 되나
postDTO 내 postAssets에는 참조 관계가 맺혀 있지 않습니다.

###질문
1. 위의 파일 업로드 방법은 잘못됐거나 놓친 부분이 있을까요?
2. postAssets만 관리하는 service가 있나요?
3. 따로 게시물과 참조 관계가 있는 postAssets정보만 찾을 수 있는 방법이 있을까요?

**Comment by hongin81** [comment]
일단 PostDTO 에 PostAsset 정보는 매핑되어 있습니다.
하지만 https://github.com/rchemist/demo-micro-front-mono/issues/4 와 같은 이슈로 정상적으로 데이터가 내려가지 않는것 같습니다.
해당 이슈 처리 시 해결될 것으로 보입니다.

PostAsset 만 처리하는 Service 는 현재 없습니다. 추가하도록 하겠습니다.
