### ISSUE TITLE
SSO로그인 접근 시 비밀번호 체크 건

### ISSUE THREAD

**Issue by seminlee0** [rchemist/demo-micro-front-mono#7]
안녕하세요.

### SSO로그인 테스트 진행
```
AuthenticationResponse response = this.loginService.requestSignin(request);
PlatformAuthenticationToken tokenRequest = new PlatformAuthenticationToken(response.getUsername(), response.getPassword()
        , new ArrayList(), response.getSiteType(), (String)null, response.getTenantAlias(), response.getSiteAlias());
ResponseData<Token> result = this.gatewayTokenAuthenticationService.createAccessToken(tokenRequest);
```

'USER정보를 찾을 수 없습니다.' 메세지 출력
`2022-04-03 21:53:06.764  INFO 368 --- [nio-8000-exec-1] i.r.c.security.SecurityLoginController   : >>> response: AuthenticationResponse(siteType=FRONT, username=refltest1, password=$2a$10$FFB.AMIj3bOVaDNhh0H0XOba3UC90kxJBZSd/1nTybTtGCFBojKL6, userId=c9cda020-cba5-4f2c-bd2e-fb9357b64277, tenantAlias=defaultTenant, siteAlias=defaultsite, roles=[ROLE_USER], enabled=true, accountNonLocked=true, accountNonExpired=true, credentialsNonExpired=true)`

현재는 response = this.loginService.requestSignin(request);에서 추출되는 response.getPassword() 값은 단방향 암호화가 진행되어 있는 상태라 'USER정보를 찾을 수 없습니다.' 에러 메세지를 출력하고 있는 것으로 파악됩니다.

### 수정 또는 추가 기능 요청(간단하게 처리하기 위한 방안을 전제로 합니다.)
> SSO로그인 진행할 때는 비밀번호 체킹하지 않는다는 인자값을 전달하여 비밀번호는 체킹하지 않고 인증을 만들어주는 로직 구현

확인 부탁드리며, 잘못 사용하고 있거나, 다른 방안으로 진행이 필요하시다면 가이드 부탁 드리겠습니다.

감사합니다.

**Comment by kunner** [comment]
혹시 platform.config.customer.simple-authentication=true 설정이 되어 있는 상태인지 확인 부탁드립니다. 

만약 해당 설정이 되어 있는데도 문제가 있다면 내일 오전 중으로 문제 확인해 드릴게요. 

참고로 위 설정에 대한 안내는 지난 번 이슈#1 번에 해 드렸습니다.

**Comment by seminlee0** [comment]
```
@Value("${platform.config.customer.simple-authentication:true}")
protected boolean simpleAuthentication;   
```


```
@Transactional
public AuthenticationResponse requestSignin(
        AuthenticationRequest request) throws AuthenticationException {

    validateRequest(request.getTenantAlias(), request.getSiteAlias());

    Customer customer = customerService.findCustomerByUsername(request.getUsername());

    boolean failure = isSigninFailure(request, customer);

    if(failure)
        throw new AuthenticationException(AuthenticationErrorType.USER_NOT_FOUND);

    AuthenticationResponse response = getAuthenticationResponse(customer);

    return response;
}
```

위와 같이 가이드 주신 부분으로 구현해두었습니다. 이 부분에서 response에 값까지 받아오지만, 패스워드 부분에서 이미 암호화 되어 있는 값이라서 에러 메세지를 출력하게 되는 것 같습니다.

```
PlatformAuthenticationToken tokenRequest = new PlatformAuthenticationToken(response.getUsername(), **response.getPassword()**
        , new ArrayList(), response.getSiteType(), (String)null, response.getTenantAlias(), response.getSiteAlias());
ResponseData<Token> result = this.gatewayTokenAuthenticationService.createAccessToken(tokenRequest);
```

대응해주셔서 감사합니다.

**Comment by kunner** [comment]
구현해 두었다는 말씀이 어떤 얘긴지 모르겠네요.

원래 의도대로라면 application properties 설정 외 따로 구현해야 할 부분이 없거든요. 

혹시 깃 주소 지난 번에 알려주신 부분에서 관련 코드가 어떤 클래스 인지 알려 주시면 내일 바로 확인해 보겠습니다.

**Comment by seminlee0** [comment]
SecurityLoginController.java
> /simple-login-test: 테스트를 위해 작성되었습니다. SSO로그인 처리 후 바로 로그인 인증은 아래의 LoginService.requestUserInfo 에서 진행됩니다.

LoginService.java
> SSO 로그인 처리를 위해 가이드 주신 방법으로 작성되어 있습니다.

**Comment by hongin81** [comment]
위에서 얘기한 것과 같이 platform.config.customer.simple-authentication:true 에 대한 설정을 하지 않아 나타난 문제입니다.
application.yml 에 설정후 이상없이 로그인 테스트 진행되었습니다.

ceratalktalk-fron 프로젝트에 커밋해놨으니 확인해보세요.
